.MODEL SMALL
.STACK 100H
.DATA
LOOP_STRING DB "LOOP",13,10,"$"
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    MOV CX, 10
    MOV AH, 9    ; CHANGE KORAR DORKAR NAI RAZIN BOLSE
PRINT_LOOP:
    LEA DX, LOOP_STRING
    INT 21H
    DEC CX
    JNZ PRINT_LOOP

    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN 